### ISSUE TITLE
拍照签到的逻辑判断有问题

### ISSUE THREAD

**Issue by Tilie** [miaochenxi/chaoxing-sign-cli#10]
"[注意]是否为拍照签到(y是, n否): "
输入了n还是签掉了

**Comment by miaochenxi** [comment]
没有问题，输入n，不上传照片(普通签到)，输入y，提交照片，拍照签到。输入n，自然按照普通签到完成

**Comment by miaochenxi** [comment]
我再修改一下，避免误解
