### ISSUE TITLE
登陆成功之后马上就失效了

### ISSUE THREAD

**Issue by conceay** [miaochenxi/chaoxing-sign-cli#11]
![image](https://user-images.githubusercontent.com/76985627/158926782-059dcf53-c41d-4407-a948-b8ebaf3cb5ac.png)
如图

**Comment by miaochenxi** [comment]
cookie过期了，登录可以通过凭据正常登，检测活动不行，必须要更新cookie，用手机号和密码再登录一下就可以了

**Comment by conceay** [comment]
登录了几次还是失效了。。

**Comment by miaochenxi** [comment]
> 登录了几次还是失效了。。

是输入手机号和密码登录的吗。

**Comment by conceay** [comment]
嗯嗯

**Comment by conceay** [comment]
不知道啥原因，stash之后重新拉库，登录还是失效

**Comment by miaochenxi** [comment]
我把cookie的内容修改了之后，试了一下没有问题啊，手动重新登陆之后，信息也被更新了一切正常。
你把项目删了，再重新克隆，运行试试看

**Comment by conceay** [comment]
> 我把cookie的内容修改了之后，试了一下没有问题啊，手动重新登陆之后，信息也被更新了一切正常。
> 
> 你把项目删了，再重新克隆，运行试试看

好，谢谢大佬。待会儿回去试试
