### ISSUE TITLE
能提供API方式就更好了

### ISSUE THREAD

**Issue by UPman24** [miaochenxi/chaoxing-sign-cli#13]

**Comment by miaochenxi** [comment]
API在有个Python写的的签到工具里提供了有好像。个人认为，提供API就容易出现“中间商”坑人的情况。

**Comment by miaochenxi** [comment]
API在有个Python写的的签到工具里提供了有好像。个人认为，提供API就容易出现“中间商”坑人的情况。

**Comment by miaochenxi** [comment]
你建议的api，写好了 :D

**Comment by UPman24** [comment]
> 你建议的api，写好了 :D

太好了
