### ISSUE TITLE
这个是自动打开的吗 为什么我搭建了服务端  你必须点一下他才打开 而且每次都要填写位置信息 或者二维码信息

### ISSUE THREAD

**Issue by HankMo** [miaochenxi/chaoxing-sign-cli#14]
这个是自动打开的吗 为什么我搭建了服务端  你必须点一下他才打开 而且每次都要填写位置信息 或者二维码信息

**Comment by miaochenxi** [comment]
没有自动签到的功能，一切都是手动的。只是提供了个签到的接口和前端页面，部署完直接打开网页签。

提供的接口你可以按照自己的需要二次开发，编写你需要的功能，比如自动签到。但是不建议用自动签到，容易被认定为异常的账号和ip，一段时间内干什么都要让你填验证码。
