### ISSUE TITLE
账户密码登陆后显示身份过期，请手动填写用户名密码。每次都这样

### ISSUE THREAD

**Issue by Meteorsss** [miaochenxi/chaoxing-sign-cli#17]
账户密码登陆后显示
登录成功
你好
身份过期，程序将关闭，请手动填写用户名密码。每次都这样

**Comment by miaochenxi** [comment]
手动输入用户名再次密码登录就行了

**Comment by Meteorsss** [comment]
就是手动输入的，显示的上面内容。我又用了自己的号（绑定学校+实名）可以正常使用，这个登不上的号是新注册的，没有绑定单位和实名，和这个有关系么？

**Comment by Meteorsss** [comment]
就是手动输入的，显示的上面内容。我用了自己的号（绑定学校+实名）可以正常使用，这个登不上的号是新注册的，没有绑定单位和实名，和这个有关系么？先登的自己的号正常，后登的新注册的号失败，在手机上用的Termux。

**Comment by miaochenxi** [comment]
> 就是手动输入的，显示的上面内容。我用了自己的号（绑定学校+实名）可以正常使用，这个登不上的号是新注册的，没有绑定单位和实名，和这个有关系么？先登的自己的号正常，后登的新注册的号失败，在手机上用的Termux。

没遇到过这情况还真难弄清楚，不过学校代码在每处功能基本上都要用到，可能和它有关吧。
