### ISSUE TITLE
抓包问题

### ISSUE THREAD

**Issue by Ricardowindoy** [miaochenxi/chaoxing-sign-cli#20]
请问大佬怎么对app进行抓包的 fiddle抓不了貌似会检测证书

**Comment by miaochenxi** [comment]
可以用 httpcanary ，root之后可以把ssl证书加入到系统证书里。
安卓上也可以用 tcpdump，然后把数据包放在wireshark里打开分析。 
fiddler也可以用，你再仔细查查用法。
还可以在linux用 arpspoof 欺骗网关和手机，当中间人转发他们俩的数据包，流量就经过自身网卡了，在wireshark上分析即可。关于HTTPS流量解密，可以百度一下
