### ISSUE TITLE
可以出一个服务器搭建完整ui的教程嘛

### ISSUE THREAD

**Issue by gongjiageng** [miaochenxi/chaoxing-sign-cli#21]
可以出一个服务器搭建完整ui的教程嘛，搭建了半天不行

**Comment by miaochenxi** [comment]
> 可以出一个服务器搭建完整ui的教程嘛，搭建了半天不行

这个其实放在腾讯云开发cloudbase里的静态网页部署就行了。巨简单。别忘了改接口地址就行

**Comment by gongjiageng** [comment]
> > 可以出一个服务器搭建完整ui的教程嘛，搭建了半天不行
> 
> 这个其实放在腾讯云开发cloudbase里的静态网页部署就行了。巨简单。别忘了改接口地址就行

![image](https://user-images.githubusercontent.com/78600910/162554596-e9a162ac-3262-485f-91e3-1235eff3c0c3.png)
大佬，这个我用服务器node部署之后，cli可以部署成功，但是ui界面用同样的方法不行，我cli用的5000的端口，ui用的3000.而且还有一个问题，我一运行那个服务，服务器负载cpu直接拉满。可以请教一下你嘛

**Comment by miaochenxi** [comment]
负载拉满还真没遇到过😂，我也不知道为什么。
ui项目应该运行npm build构建出静态网页，装个Nginx，部署静态网页。

**Comment by miaochenxi** [comment]
https://create-react-app.dev/docs/deployment
