### ISSUE TITLE
用户身份过期 Bug

### ISSUE THREAD

**Issue by killlowkey** [miaochenxi/chaoxing-sign-cli#25]
# 问题原因
使用账号密码登陆成功后，出现 “身份过期” 提示
![Snipaste_2022-04-19_12-34-13](https://user-images.githubusercontent.com/41176828/163921809-a348ded2-bde5-4d2e-b63f-e1c9c3068be1.png)
之后翻看了 user.js 源代码，代码对响应码 302 进行判断，但 302 是一个重定向响应，明显不是身份过期原因
![Snipaste_2022-04-19_12-48-42](https://user-images.githubusercontent.com/41176828/163922238-f380e454-28be-4b9a-b240-cba2227e7fe2.png)
这让我很疑惑了，然后翻看了 COURSELIST.URL（`http://mooc1-1.chaoxing.com/visit/courselistdata`）接口，发现该接口是用于获取 **所教课程**，并不能获取到 **加入课程**。
为了验证我的想法，在学习通中创建了一门课程，登陆后，发现可以正常使用。
![Snipaste_2022-04-19_12-39-53](https://user-images.githubusercontent.com/41176828/163922891-4177e499-6dfe-43eb-8011-7453a7b5a9d8.png)
![Snipaste_2022-04-19_12-42-26](https://user-images.githubusercontent.com/41176828/163922910-928c9b13-7e7f-4761-9de3-cff9433b5fcc.png)

# 解决方法
将 COURSELIST.URL 换成获取**加入课程**接口，接口我就懒得抓了，还请作者修复一下 哈

**Comment by miaochenxi** [comment]
302重定向让你登录…所以是过期

**Comment by killlowkey** [comment]
> 302重定向让你登录…所以是过期

还是用一个没有创建过课程的学习通账号试试吧，我也看了 issue，如果只是单纯身份过期问题，怎么会有好几个人提 issue。
绝对不可能是身份过期的原因，怎么可能登陆后直接秒失效

**Comment by miaochenxi** [comment]
极个例出现这个问题，不清楚是怎么出现的。

但是普遍使用情况下，学生认证且绑定学校的且有加入的课程的并且有活动的，没遇到过这个情况。另外你说的 courselistdata 接口，在上述的普遍情况下，获取的就是所加入的课程，而不是所教课程。
![image](https://user-images.githubusercontent.com/32982052/163926235-d7696519-9fd2-40ff-a8ba-0d2b36cbdcfc.png)

这个稀有情况，相对与普遍情况，我暂时没办法在不影响普遍的前提下解决它。

**Comment by miaochenxi** [comment]
相关议题

https://github.com/miaochenxi/chaoxing-sign-cli/issues/17#issuecomment-1090346426

https://github.com/miaochenxi/chaoxing-sign-cli/issues/11#issue-1173120773

**Comment by miaochenxi** [comment]
这里看到你和 Issue#17 都没显示出姓名，原因可能一样。

这个签到项目只针对普遍的使用情况来进行下去，没有绑定学校+实名认证的账号，我觉得不会有课程签到，也没必要针对这个开发

**Comment by killlowkey** [comment]
> 这里看到你和 Issue#17 都没显示出姓名，原因可能一样。
> 
> 这个签到项目只针对普遍的使用情况来进行下去，没有绑定学校+实名认证的账号，我觉得不会有课程签到，也没必要针对这个开发

也许可以换个方式获取课程接口，刚才我抓取了学习通app包，并且我也在浏览器访问过了，在学习通账号登陆前提下，可以获取到课程
接口（Get请求）：http://mooc1-api.chaoxing.com/mycourse/backclazzdata?view=json&rss=1

**Comment by miaochenxi** [comment]
这个接口也可用，但是影响获取活动的效率。
这个接口获取的是加入的全部课程，而现在使用的接口获取的是未加入其他文件夹的课程，也就是根目录的课程。比如已经结束了的课程，加入其他文件夹，使用当前接口获取列表时就只会列出根目录的课，课程少遍历起来快，体验更好。

**Comment by killlowkey** [comment]
> 这个接口也可用，但是影响获取活动的效率。
> 这个接口获取的是加入的全部课程，而现在使用的接口获取的是未加入其他文件夹的课程，也就是根目录的课程。比如已经结束了的课程，加入其他文件夹，使用当前接口获取列表时就只会列出根目录的课，课程少遍历起来快，体验更好。

那这个接口不能加到备选接口嘛，比如主接口获取不到数据，在使用该接口获取。既不影响普通用户，也能使其他用户可用

**Comment by miaochenxi** [comment]
待会写进去🥹

**Comment by killlowkey** [comment]
> 待会写进去🥹

好的👌
