### ISSUE TITLE
增加配置文件

### ISSUE THREAD

**Issue by d4renk** [miaochenxi/chaoxing-sign-cli#27]
**每次签到手动输入用户，还得确认是否拍照签到，老师上课喜欢发布十秒签到，用命令行签不赢**

**Comment by miaochenxi** [comment]
普通签到有 是否提交照片 的选项，所以必须确认是否是拍照签到。

你可以直接修改 index.js 中的 case: 0，把别的代码删了，只剩下普通签到直接签

**Comment by miaochenxi** [comment]
嫌麻烦的话就部署带界面的项目吧，签到用手点两三下就行了

**Comment by d4renk** [comment]
> 普通签到有 是否提交照片 的选项，所以必须确认是否是拍照签到。
> 
> 你可以直接修改 index.js 中的 case: 0，把别的代码删了，只剩下普通签到直接签

位置签到只会在本校签到，能否增加位置签到配置文件

**Comment by miaochenxi** [comment]
在index.js的 case 4中：
LocationSign (uf: any, _d: any, vc3: any, name: any, "地址", activeId: any, uid: any, 33.150294, 113.873951, fid: any)
其他参数默认不用管，把这俩数字和地址修改一下，写死在代码里就行了。最便捷。
然后可以把case4 里面的询问填写代码删了。就直接按照你写进去的签。

最近忙着找找实习，没空维护这个了
