### ISSUE TITLE
你好作者，我在服务器搭建完cli和ui端，接口服务和前端页面都正常运行，在ui页面点击确认添加浏览器无反应

### ISSUE THREAD

**Issue by xinchenmi** [miaochenxi/chaoxing-sign-cli#28]
<img width="960" alt="1651057843" src="https://user-images.githubusercontent.com/74248712/165505841-6bd65ef0-c1d7-409b-ba44-15f028cf04af.png">
你好作者，我在服务器搭建完cli和ui端，接口服务和前端页面都正常运行，在ui页面点击确认添加浏览器无反应，请问这是怎么回事呢

**Comment by miaochenxi** [comment]
相关issue：
https://github.com/miaochenxi/chaoxing-sign-ui/issues/2
https://github.com/miaochenxi/chaoxing-sign-ui/issues/7

**Comment by xinchenmi** [comment]
> 相关issue： [miaochenxi/chaoxing-sign-ui#2 ](https://github.com/miaochenxi/chaoxing-sign-ui/issues/2) [miaochenxi/chaoxing-sign-ui#7](https://github.com/miaochenxi/chaoxing-sign-ui/issues/7)

感谢
