### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xiaofengv233** [miaochenxi/chaoxing-sign-cli#3]
![Screenshot_2021-11-08-15-48-04-422_com termux](https://user-images.githubusercontent.com/24617660/140703365-74c5cb82-fc66-42e2-aab6-646d9b6daf79.jpg)
pkg install git https://github.com/miaochenxi/chaoxing-sign-cli.git
输入了之后就这样

**Comment by miaochenxi** [comment]
截图中看到您并没有按照教程来操作。

如果没有 git 请使用 `pkg install git` 来安装，而您运行的是 `pkg install git https://github.com/miaochenxi/chaoxing-sign-cli.git`，这是错误的。

安装完 git 以后，运行 `git clone https://github.com/miaochenxi/chaoxing-sign-cli.git` ，克隆项目，并根据教程继续操作。

**Comment by xiaofengv233** [comment]
> 截图中看到您并没有按照教程来操作。
> 
> 如果没有 git 请使用 来安装，而您运行的是 ，这是错误的。`pkg install git``pkg install git https://github.com/miaochenxi/chaoxing-sign-cli.git`
> 
> 安装完 git 以后，运行 ，克隆项目，并根据教程继续操作。`git clone https://github.com/miaochenxi/chaoxing-sign-cli.git`

哦哦

> 截图中看到您并没有按照教程来操作。
> 
> 如果没有 git 请使用 `pkg install git` 来安装，而您运行的是 `pkg install git https://github.com/miaochenxi/chaoxing-sign-cli.git`，这是错误的。
> 
> 安装完 git 以后，运行 `git clone https://github.com/miaochenxi/chaoxing-sign-cli.git` ，克隆项目，并根据教程继续操作。

哦哦原来是这样 我的错 。。。。
