### ISSUE TITLE
学习通现在貌似检测不到签到任务了

### ISSUE THREAD

**Issue by DoffChen** [miaochenxi/chaoxing-sign-cli#4]
目前没有办法检测到签到任务,无法签到,有没有什么好的解决方案

**Comment by miaochenxi** [comment]
把课程码发一下邀请我进你的课程吧，你发布一个签到，我试一下

**Comment by DoffChen** [comment]
好的
![gen2DimensionalBarCode](https://user-images.githubusercontent.com/45647558/141142063-a8f88da0-899b-4a05-ba75-d56c56a7a3f5.png)
,这里是课程二维码

**Comment by DoffChen** [comment]
大佬会不会是我账号被屏蔽了,因为之前一直挂云函数在跑
