### ISSUE TITLE
位置签到未能检测到有效签到活动

### ISSUE THREAD

**Issue by oneohyes** [miaochenxi/chaoxing-sign-cli#6]
手机上已经收到位置签到了，但是脚本上还是显示这个。
也没有报错什么的。
难道是反应比较慢？
看了一下，那个签到是属于班级的，没有在课程里面，难道是不属于课程的里面的就没法签？

**Comment by miaochenxi** [comment]
目前只能签课程的签到活动，班级签到我还没遇到过。
![image](https://user-images.githubusercontent.com/32982052/147062325-8733135c-cb5d-4cb9-8e17-90aae98412af.png)
