### ISSUE TITLE
请问这个能够进行一个或者多个定时任务吗？

### ISSUE THREAD

**Issue by Gypsophila-Z** [miaochenxi/chaoxing-sign-cli#8]
实在是无法预测到老师什么时候签到，跑去厕所的功夫就已经签到过期了，害。

**Comment by miaochenxi** [comment]
亲亲，这个建议你fork一份自己修改一下，用setInterval周期性获取签到活动就行了，请求太多太频繁我觉得这样对它服务器是一种DDOS，容易搞得账号异常。
最好的解决办法，还是关注学习通微信公众号，有活动就会发消息通知你。如果你看不到，手机上安装通知过滤app，匹配到学习通字段就语音播报通知内容，把你叫起来。

**Comment by Gypsophila-Z** [comment]
好的，了解了。谢谢你
