### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by conceay** [miaochenxi/chaoxing-sign-cli#9]
大佬，想问下你是自学的吗？我现在正在学前端，已经到JS了，可以指点下你的学习路线吗

**Comment by miaochenxi** [comment]
> 大佬，想问下你是自学的吗？我现在正在学前端，已经到JS了，可以指点下你的学习路线吗

我辣鸡死了😢.......
我是最开始那基础三件套(HTML、CSS、js)学个差不多，不算多好但是也熟练使用没问题。之后就用它模仿写了个Android开发官网的首页。再后来有了这些基础，去学vue，那时时间也早，我想多试试，所以后来又去学了学react，都是学到能用框架顺利写几小小项目程度，不算好但是也不算差。后来决定哪个框架适合我，我选择react，打算慢慢学好react，学精学熟。node我从头到尾一直多多少少学学写写，写过接口，写过这种签到程序，抓包的过程，找到关键地方和模仿它请求真的挺有意思。现在学校课程比较多很麻烦，基本上在搁置这些学习，大概过了这周，就继续学了。

像npm很多有意思的模块可以去学学用用。

在上课，暂时就这些。。。

**Comment by conceay** [comment]
嗯好，我也学了html css ，js还在学，vue之前也看了点 node自己也写过东西，但是js没学完，什么promise啥的完全看不懂只会点简单的xmlhttprrquest，谢谢大佬，我再研究研究
